#!/usr/bin/env python

import os

import serial.tools.list_ports


devices = serial.tools.list_ports.comports()
match = next(
    elem for elem in devices
    if elem.serial_number == os.environ['CONTROLLINO_USB_SERIAL_NUMBER']
)

with open('platformio.ini.in', 'r') as f:
    platformio = f.read()

platformio = platformio.replace('@UPLOAD_PORT', match.device)

with open('platformio.ini', 'w') as f:
    f.write(platformio)
